### ISSUE TITLE
Create skeleton brmsfit and stanmodel objects for each model

### ISSUE THREAD

**Issue by dbarneche** [AIMS/bayesnec#11]
This needs to be added to [`data-raw/sysdata.R`](https://github.com/AIMS/bayesnec/blob/pkg_build_v1/data-raw/sysdata.R)

So then one single [`R/sysdata.rda`](https://github.com/AIMS/bayesnec/blob/pkg_build_v1/R/sysdata.rda) is created.

**Comment by dbarneche** [comment]
For this issue, it’d be great to have a list of all models allowed, broken down by family distribution @beckyfisher 
This way I can systematically implement the code to create the empty lightweight `brmsfit` objects with accompanying R functions (issue #12). After those two steps I can then integrate the calls with define_model.R (issue #13)

**Comment by beckyfisher** [comment]
@dbarneche At the moment all models allowed are currently in define_models and all families should be allowed for each, using their appropriate link function.
