### ISSUE TITLE
Which functions to export?

### ISSUE THREAD

**Issue by dbarneche** [AIMS/bayesnec#19]
I think we only need to export the main ones:
- bnec
- plot.bayesnecfit
- predict.bayesnecfit
- plot.bayesmanecfit

The users are only going to be interacting with these four functions. The remaining ones are accessories to make these four above work, so I think they don't need to be accessible by them, particularly if the main target audience is novice. The more advanced people will know to use ::: to explore not-exported functions.

What do you think?

**Comment by beckyfisher** [comment]
Sounds good to me Diego

**Comment by dbarneche** [comment]
2cbd741471a14f2dc61fdcfe794e0dabdc9c7191
