### ISSUE TITLE
Diagnostic plots of chain mixing

### ISSUE THREAD

**Issue by beckyfisher** [AIMS/bayesnec#2]
We need a function to plot chain mixing of the bmrs model fit, to produce something similar to the check.chains function at https://github.com/AIMS/NEC-estimation/blob/master/R/check_chains.R
Adding other diagnostics to the plots might also be a good idea, as a one stop place for users to view their model diagnostics.

**Comment by dbarneche** [comment]
Closing this issue, brms already provides a number of custom functions to explore posterior chains. So rather than adding these to the package, we just instruct the user on how to use them directly via brms.
