### ISSUE TITLE
Remove copyright from R files, move info to LICENSE

### ISSUE THREAD

**Issue by dbarneche** [AIMS/bayesnec#4]
Also we probably want to use MIT license

**Comment by beckyfisher** [comment]
AIMS legal recommended APACHE 2.0 when I asked them about this recently.
Also following the recommendations at https://github.com/bcgov/BC-Policy-Framework-For-GitHub/blob/master/BC-Open-Source-Development-Employee-Guide/Licenses.md that recommend putting a "boiler" plate in the comments at the header of every source file.

**Comment by dbarneche** [comment]
a4e05f1fe93afe657bd088a90d0aa7fb4d237634
